apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-path-${appname}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  rules:
  - host: ${domainname}
    http:
      paths:
        - backend:
            serviceName: ${appname}-app
            servicePort: 80
          path: /${appname}(/|$)(.*)
